version: "3.9"
services:
  api:
    build: .
    container_name: vimedbot_api
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./assets:/app/assets
    depends_on:
      - qdrant
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    restart: unless-stopped

volumes:
  qdrant_storage: